name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
      - uses: actions/setup-node@v2.4.0
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read
      # - run: npx token-transformer tokens.json tokens/global.json global
      # Create a light theme, exclude the global tokens
      - run: npx token-transformer tokens.json theia/dark.json core,ide-dark,theia core,ide-dark
      # Create a dark theme, exclude the global tokens
      - run: npx token-transformer tokens.json theia/default.json core,ide-default,theia core,ide-default
      # Convert tokens according to Style Dictionary config
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - name: Git Auto Commit
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
        commit_message: Update Tokens
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Update Tokens